x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"

x-default-settings: &default-settings
  restart: unless-stopped
  privileged: false
  read_only: true  # Prod uses a read-only fs, override this locally if it helps with debugging
  user: "65534"  # Prod uses a non-root user, override this locally if it helps with debugging

services:
  postgres:
    logging: *logging
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:7777:5432"
    environment:
      POSTGRES_DB: codejam_management
      POSTGRES_PASSWORD: codejam_management
      POSTGRES_USER: codejam_management
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U codejam_management" ]
      interval: 2s
      timeout: 1s
      retries: 5

  api:
    << : *default-settings
    logging: *logging
    build:
      context: .
      args:
        - uvicorn_extras=--reload
    volumes:
      - ./alembic/versions:/app/alembic/versions
      - .:/app:ro
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://codejam_management:codejam_management@postgres:5432/codejam_management
    ports:
      - 5000:8000
