version: "3.7"

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: codejam_management
            POSTGRES_PASSWORD: codejam_management
            POSTGRES_USER: codejam_management
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    api:
        build: .
        restart: always
        environment:
            DATABASE_URL: postgresql+asyncpg://codejam_management:codejam_management@postgres:5432/codejam_management
        ports:
            - 5000:5000
