"""Create tables

Revision ID: 103ccfde4460
Revises:
Create Date: 2021-07-19 11:13:00.072173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "103ccfde4460"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users", sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "infractions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("jam_id", sa.Integer(), nullable=True),
        sa.Column("infraction_type", sa.Enum("note", "ban", "warning", name="infraction_type"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jam_id"],
            ["jams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jam_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jam_id"],
            ["jams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "winners",
        sa.Column("jam_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_place", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jam_id"],
            ["jams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("jam_id", "user_id"),
    )
    op.create_table(
        "team_has_user",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_leader", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_has_user")
    op.drop_table("winners")
    op.drop_table("teams")
    op.drop_table("infractions")
    op.drop_table("users")
    op.drop_table("jams")
    # ### end Alembic commands ###
