"""Add jam column

Revision ID: 89e175c77aea
Revises: 103ccfde4460
Create Date: 2022-02-26 10:50:02.103189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89e175c77aea'
down_revision = '103ccfde4460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jams', sa.Column('ongoing', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jams', 'ongoing')
    # ### end Alembic commands ###
