"""Add Discord identifiers to Team

Revision ID: a2c25c740f2a
Revises: 89e175c77aea
Create Date: 2022-06-30 13:36:06.884827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2c25c740f2a"
down_revision = "89e175c77aea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("discord_role_id", sa.BigInteger(), nullable=True))
    op.add_column("teams", sa.Column("discord_channel_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "discord_channel_id")
    op.drop_column("teams", "discord_role_id")
    # ### end Alembic commands ###
