CREATE TABLE IF NOT EXISTS jams (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    CONSTRAINT jams_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teams (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jam_id int references jams(id) NOT NULL,
    "name" text NOT NULL,
    CONSTRAINT teams_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id bigint NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS team_has_user (
    team_id int references teams(id) NOT NULL,
    user_id bigint references users(id) NOT NULL,
    is_leader boolean NOT NULL,
    CONSTRAINT team_has_user_pk PRIMARY KEY (team_id, user_id)
);

CREATE TABLE IF NOT EXISTS winners (
    jam_id int references jams(id) NOT NULL,
    user_id bigint references users(id),
    first_place boolean NOT NULL,
    CONSTRAINT winners_pk PRIMARY KEY (jam_id, user_id)
);

CREATE TYPE infraction_type AS ENUM (
    'note',
    'ban',
    'warning'
);

CREATE TABLE IF NOT EXISTS infractions (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint references users(id),
    jam_id int references jams(id),
    infraction_type infraction_type NOT NULL,
    reason text NOT NULL,
    CONSTRAINT infractions_pk PRIMARY KEY (id)
);
